import { formatRevenue } from "@/lib/operations/metrics";

type DocumentLineItem = {
  description: string;
  quantity: number;
  unitPriceCents: number;
  totalCents: number;
};

type DocumentInput = {
  type: "quote" | "invoice" | "receipt";
  documentNumber: string;
  companyName: string;
  companyEmail?: string | null;
  companyPhone?: string | null;
  customerName: string;
  customerEmail?: string | null;
  status: string;
  lineItems: DocumentLineItem[];
  subtotalCents: number;
  discountCents: number;
  taxCents: number;
  totalCents: number;
  amountPaidCents?: number;
  balanceDueCents?: number;
  notes?: string | null;
  dueDate?: string | null;
  validUntil?: string | null;
  issuedAt?: string | null;
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function renderFinancialDocumentHtml(input: DocumentInput): string {
  const title =
    input.type === "quote"
      ? "Quote"
      : input.type === "receipt"
        ? "Receipt"
        : "Invoice";

  const rows = input.lineItems
    .map(
      (li) => `<tr>
        <td>${escapeHtml(li.description)}</td>
        <td style="text-align:right">${li.quantity}</td>
        <td style="text-align:right">${formatRevenue(li.unitPriceCents)}</td>
        <td style="text-align:right">${formatRevenue(li.totalCents)}</td>
      </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)} ${escapeHtml(input.documentNumber)}</title>
  <style>
    body { font-family: system-ui, sans-serif; color: #0f172a; margin: 40px; }
    h1 { margin: 0 0 4px; font-size: 28px; }
    .muted { color: #64748b; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 24px; }
    th, td { border-bottom: 1px solid #e2e8f0; padding: 10px 8px; text-align: left; }
    th { font-size: 12px; text-transform: uppercase; color: #64748b; }
    .totals { margin-top: 24px; width: 280px; margin-left: auto; }
    .totals div { display: flex; justify-content: space-between; padding: 6px 0; }
    .total-row { font-weight: 700; font-size: 18px; border-top: 2px solid #0f172a; padding-top: 10px; }
    .status { display: inline-block; padding: 4px 10px; border-radius: 999px; background: #f1f5f9; font-size: 12px; text-transform: capitalize; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(input.companyName)}</h1>
    <p class="muted">
      ${input.companyEmail ? escapeHtml(input.companyEmail) : ""}
      ${input.companyPhone ? ` · ${escapeHtml(input.companyPhone)}` : ""}
    </p>
  </header>

  <section style="margin-top:32px;display:flex;justify-content:space-between;gap:24px;">
    <div>
      <p class="muted">${escapeHtml(title)}</p>
      <p style="font-size:20px;font-weight:700;">${escapeHtml(input.documentNumber)}</p>
      <p><span class="status">${escapeHtml(input.status.replace(/_/g, " "))}</span></p>
    </div>
    <div style="text-align:right">
      <p class="muted">Bill to</p>
      <p style="font-weight:600;">${escapeHtml(input.customerName)}</p>
      ${input.customerEmail ? `<p class="muted">${escapeHtml(input.customerEmail)}</p>` : ""}
      ${input.dueDate ? `<p class="muted">Due: ${escapeHtml(input.dueDate)}</p>` : ""}
      ${input.validUntil ? `<p class="muted">Valid until: ${escapeHtml(input.validUntil)}</p>` : ""}
    </div>
  </section>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th style="text-align:right">Qty</th>
        <th style="text-align:right">Unit price</th>
        <th style="text-align:right">Total</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <div><span>Subtotal</span><span>${formatRevenue(input.subtotalCents)}</span></div>
    ${input.discountCents > 0 ? `<div><span>Discount</span><span>-${formatRevenue(input.discountCents)}</span></div>` : ""}
    ${input.taxCents > 0 ? `<div><span>Tax</span><span>${formatRevenue(input.taxCents)}</span></div>` : ""}
    <div class="total-row"><span>Total</span><span>${formatRevenue(input.totalCents)}</span></div>
    ${input.amountPaidCents != null ? `<div><span>Paid</span><span>${formatRevenue(input.amountPaidCents)}</span></div>` : ""}
    ${input.balanceDueCents != null ? `<div><span>Balance due</span><span>${formatRevenue(input.balanceDueCents)}</span></div>` : ""}
  </div>

  ${input.notes ? `<p style="margin-top:32px;" class="muted"><strong>Notes:</strong> ${escapeHtml(input.notes)}</p>` : ""}

  <p class="muted" style="margin-top:48px;">Generated by Shalean</p>
</body>
</html>`;
}
